package com.secretvault.auth.stepup.model;

/**
 * Enumeration of sensitive operations eligible for Step-Up Authentication.
 */
public enum StepUpAction {
    SECRET_REVEAL,
    SECRET_DELETE,
    SECRET_ROLLBACK,
    ENVIRONMENT_PROMOTE,
    ACCESS_GRANT,
    ACCESS_REVOKE,
    JIT_APPROVE,
    JIT_REVOKE,
    MFA_DISABLE,
    SESSION_REVOKE_ALL,
    WEBAUTHN_CREDENTIAL_REVOKE,
    ROLE_CHANGE,
    MEMBER_REMOVE,
    PROJECT_ACCESS_CHANGE,
    ENVIRONMENT_ACCESS_CHANGE,
    PRIVILEGED_POLICY_CHANGE,
    BREAK_GLASS_REQUEST,
    PRIVILEGED_APPROVE,
    PRIVILEGED_EXECUTE
}
