package com.secretvault.audit.entity;

/**
 * Enumeration of audited security, lifecycle, and access governance actions.
 */
public enum AuditAction {
    SECRET_CREATED,
    SECRET_METADATA_UPDATED,
    SECRET_VALUE_UPDATED,
    SECRET_REVEALED,
    SECRET_HISTORICAL_REVEALED,
    SECRET_DELETED,
    SECRET_DISABLED,
    SECRET_ENABLED,
    SECRET_ROLLBACK_COMPLETED,
    SECRET_VERSION_TAGGED,
    SECRET_VERSION_UNTAGGED,
    SECRET_BRANCH_CREATED,
    SECRET_BRANCH_COMMITTED,
    SECRET_BRANCH_MERGED,
    SECRET_BRANCH_ARCHIVED,
    SECRET_PROMOTION_COMPLETED,
    WORKSPACE_SETTINGS_UPDATED,
    PROJECT_ACCESS_GRANTED,
    PROJECT_ACCESS_REVOKED,
    ENVIRONMENT_ACCESS_GRANTED,
    ENVIRONMENT_ACCESS_REVOKED,

    // Phase 5 Access Control, JIT & Reviews
    ACCESS_GRANT_CREATED,
    ACCESS_GRANT_REVOKED,
    JIT_ACCESS_REQUESTED,
    JIT_ACCESS_APPROVED,
    JIT_ACCESS_REJECTED,
    JIT_ACCESS_REVOKED,
    JIT_ACCESS_CANCELLED,
    ACCESS_REVIEW_CAMPAIGN_CREATED,
    ACCESS_REVIEW_ITEM_DECIDED,
    ACCESS_REVIEW_CAMPAIGN_COMPLETED,

    // Phase 7 Provider Integrations
    PROVIDER_INTEGRATION_CREATED,
    PROVIDER_INTEGRATION_UPDATED,
    PROVIDER_INTEGRATION_DISABLED,
    PROVIDER_INTEGRATION_DELETED,
    PROVIDER_INTEGRATION_VALIDATED,
    PROVIDER_MAPPING_CREATED,
    PROVIDER_MAPPING_UPDATED,
    PROVIDER_MAPPING_DELETED,
    PROVIDER_SECRET_PUSHED,
    PROVIDER_SECRET_DELETED,
    PROVIDER_OPERATION_FAILED,

    // Team Invitations & Member Governance
    INVITATION_CREATED,
    INVITATION_ACCEPTED,
    INVITATION_DECLINED,
    INVITATION_REVOKED,
    MEMBER_ROLE_CHANGED,
    MEMBER_REMOVED,

    // Phase 5.7 MFA & Authentication Hardening
    MFA_ENROLLMENT_STARTED,
    MFA_ACTIVATED,
    MFA_DISABLED,
    MFA_CHALLENGE_ISSUED,
    MFA_VERIFICATION_SUCCESS,
    MFA_VERIFICATION_FAILED,
    MFA_CHALLENGE_EXPIRED,
    MFA_CHALLENGE_LOCKED,
    MFA_RECOVERY_CODE_USED
}
