package com.secretvault.audit.entity;

/**
 * Enumeration of audited security, lifecycle, and access governance actions.
 */
public enum AuditAction {
    SECRET_CREATED,
    SECRET_METADATA_UPDATED,
    SECRET_VALUE_UPDATED,
    SECRET_REVEALED,
    SECRET_HISTORICAL_REVEALED,
    SECRET_DELETED,
    SECRET_DISABLED,
    SECRET_ENABLED,
    SECRET_ROLLBACK_COMPLETED,
    SECRET_VERSION_TAGGED,
    SECRET_VERSION_UNTAGGED,
    SECRET_BRANCH_CREATED,
    SECRET_BRANCH_COMMITTED,
    SECRET_BRANCH_MERGED,
    SECRET_BRANCH_ARCHIVED,
    SECRET_PROMOTION_COMPLETED,
    WORKSPACE_SETTINGS_UPDATED,
    ENVIRONMENT_ACCESS_GRANTED,
    ENVIRONMENT_ACCESS_REVOKED,

    // Phase 5 Access Control, JIT & Reviews
    ACCESS_GRANT_CREATED,
    ACCESS_GRANT_REVOKED,
    JIT_ACCESS_REQUESTED,
    JIT_ACCESS_APPROVED,
    JIT_ACCESS_REJECTED,
    JIT_ACCESS_REVOKED,
    JIT_ACCESS_CANCELLED,
    ACCESS_REVIEW_CAMPAIGN_CREATED,
    ACCESS_REVIEW_ITEM_DECIDED,
    ACCESS_REVIEW_CAMPAIGN_COMPLETED
}
