package com.secretvault.audit.entity;

/**
 * Enumeration of audited security and lifecycle actions.
 */
public enum AuditAction {
    SECRET_CREATED,
    SECRET_METADATA_UPDATED,
    SECRET_VALUE_UPDATED,
    SECRET_REVEALED,
    SECRET_HISTORICAL_REVEALED,
    SECRET_DELETED,
    SECRET_DISABLED,
    SECRET_ENABLED,
    SECRET_ROLLBACK_COMPLETED,
    SECRET_VERSION_TAGGED,
    SECRET_VERSION_UNTAGGED,
    SECRET_BRANCH_CREATED,
    SECRET_BRANCH_COMMITTED,
    SECRET_BRANCH_MERGED,
    SECRET_BRANCH_ARCHIVED,
    SECRET_PROMOTION_COMPLETED,
    WORKSPACE_SETTINGS_UPDATED,
    ENVIRONMENT_ACCESS_GRANTED,
    ENVIRONMENT_ACCESS_REVOKED
}
