{{- if and .Values.secretvault.tls.caBundle (not .Values.secretvault.tls.caSecretRef) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretvault-operator.fullname" . }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secretvault-operator.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.secretvault.tls.caBundle | b64enc | quote }}
{{- end }}
