package com.secretvault.repository.model;

public enum SecretType {
    AWS_ACCESS_KEY,
    AWS_SECRET_KEY,
    GITHUB_TOKEN,
    GITLAB_TOKEN,
    GOOGLE_API_KEY,
    AZURE_CREDENTIAL,
    SLACK_TOKEN,
    STRIPE_KEY,
    TWILIO_KEY,
    SENDGRID_KEY,
    DATABASE_PASSWORD,
    DATABASE_CONNECTION_STRING,
    JWT,
    OAUTH_CLIENT_SECRET,
    PRIVATE_KEY,
    SSH_PRIVATE_KEY,
    CERTIFICATE,
    WEBHOOK_SECRET,
    GENERIC_API_KEY,
    GENERIC_TOKEN,
    GENERIC_PASSWORD,
    HIGH_ENTROPY_STRING,
    UNKNOWN_CREDENTIAL
}
