package com.secretvault.events.model;

/**
 * Authoritative taxonomy of domain event types across SecretVault.
 */
public enum EventType {
    // Secret Lifecycle Events
    SECRET_CREATED,
    SECRET_UPDATED,
    SECRET_DELETED,
    SECRET_REVEALED,
    SECRET_VERSION_CREATED,
    SECRET_ROLLBACK,
    SECRET_PROMOTED,
    SECRET_BRANCH_CREATED,
    SECRET_MERGED,
    SECRET_COMPROMISED,
    SECRET_REVOKED,
    SECRET_RESTORED,

    // Rotation Lifecycle Events
    ROTATION_POLICY_CREATED,
    ROTATION_POLICY_UPDATED,
    ROTATION_POLICY_DISABLED,
    ROTATION_TRIGGERED,
    ROTATION_STARTED,
    ROTATION_GENERATING,
    ROTATION_GENERATED,
    ROTATION_VALIDATING,
    ROTATION_VALIDATED,
    ROTATION_STAGED,
    ROTATION_ACTIVATED,
    ROTATION_GRACE_STARTED,
    ROTATION_REVOKING,
    ROTATION_COMPLETED,
    ROTATION_FAILED,
    ROTATION_ROLLED_BACK,
    ROTATION_PAUSED,
    ROTATION_RESUMED,

    // Ephemeral Lease Events
    LEASE_CREATED,
    LEASE_RENEWED,
    LEASE_EXPIRED,
    LEASE_REVOKED,
    LEASE_RENEWAL_REJECTED,

    // Consumer Lifecycle Events
    CONSUMER_REGISTERED,
    CONSUMER_HEARTBEAT,
    CONSUMER_STALE,
    CONSUMER_RECOVERED,
    CONSUMER_DISABLED,
    CONSUMER_REFRESHED,
    CONSUMER_REFRESH_FAILED,

    // Machine Identity & OIDC Workload Events
    MACHINE_CREATED,
    MACHINE_DISABLED,
    MACHINE_SUSPENDED,
    MACHINE_REVOKED,
    MACHINE_SESSION_CREATED,
    MACHINE_SESSION_REJECTED,

    // Access Governance & JIT Events
    ACCESS_GRANTED,
    ACCESS_REVOKED,
    ACCESS_EXPIRED,
    JIT_REQUESTED,
    JIT_APPROVED,
    JIT_REJECTED,
    JIT_EXPIRED,
    JIT_REVOKED,
    ACCESS_REVIEW_CREATED,
    ACCESS_REVIEW_COMPLETED,
    ACCESS_REVIEW_REMEDIATION,

    // Provider Integration & Sync Events
    PROVIDER_CONNECTED,
    PROVIDER_CONNECTION_FAILED,
    PROVIDER_SYNC_STARTED,
    PROVIDER_SYNC_COMPLETED,
    PROVIDER_SYNC_FAILED,
    PROVIDER_DRIFT_DETECTED,
    PROVIDER_DRIFT_RESOLVED,
    PROVIDER_RESOURCE_DISCOVERED,

    // Security Posture & Anomaly Events
    SECURITY_FINDING_CREATED,
    SECURITY_FINDING_RESOLVED,
    SECURITY_INCIDENT_CREATED,
    SECURITY_INCIDENT_UPDATED,
    SECURITY_INCIDENT_RESOLVED,
    SECURITY_POLICY_VIOLATION,
    ANOMALY_DETECTED,

    // System & Operational Events
    CONFIG_CHANGED,
    SCHEDULER_FAILURE,
    EVENT_PROCESSING_FAILURE,
    WEBHOOK_DELIVERY_FAILURE,
    AUTOMATION_EXECUTION_FAILURE;

    public static EventType fromString(String name) {
        if (name == null || name.isBlank()) return null;
        try {
            return EventType.valueOf(name.trim().toUpperCase());
        } catch (IllegalArgumentException e) {
            return null;
        }
    }
}
