apiVersion: secretvault.io/v1alpha1
kind: SecretVaultSecret
metadata:
  name: stripe-api-key-pinned
  namespace: billing-system
spec:
  workspace: default
  project: billing
  environment: production
  secretName: STRIPE_API_KEY
  version: 3
  versionPolicy: PINNED
  refreshInterval: 30m
  lease:
    enableLease: true
    ttl: "1800s"
    autoRenew: true
    consumerType: CONTAINER
  auth:
    serviceAccountRef:
      name: billing-workload-sa
  target:
    name: stripe-credentials
    key: api_key
    creationPolicy: Owner
