apiVersion: secretvault.io/v1alpha1
kind: SecretVaultSync
metadata:
  name: payment-environment-sync
  namespace: payment-service
spec:
  workspace: default
  project: payment-gateway
  environment: production
  refreshInterval: 15m
  driftPolicy: Enforce
  auth:
    serviceAccountRef:
      name: payment-service-sa
  target:
    secretName: payment-app-env
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: secretvault-operator
          app.kubernetes.io/part-of: payment-gateway
