apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secretvault-operator-leader-election-role
  namespace: secretvault-system
  labels:
    app.kubernetes.io/name: secretvault-operator
    app.kubernetes.io/part-of: secretvault
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
