apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretvault-operator-controller-manager
  namespace: secretvault-system
  labels:
    app.kubernetes.io/name: secretvault-operator
    app.kubernetes.io/part-of: secretvault
