spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:secretvault_dev}}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:vault_user}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:vault_secure_password_dev_only}}
    driver-class-name: org.postgresql.Driver

secretvault:
  security:
    master-key: ${VAULT_MASTER_KEY:dGVzdF9tYXN0ZXJfa2V5XzMyX2J5dGVzX2Rldl8wMDE=}
    jwt:
      secret: ${JWT_SECRET:super_secret_jwt_signing_key_for_local_development_only_minimum_256_bits_length}

logging:
  level:
    root: INFO
    com.secretvault: DEBUG
    org.springframework.security: INFO
    org.flywaydb: INFO
